import { Product } from "./types";

export const seedProducts: Product[] = [
  {
    id: "p1",
    title: "vivo Y17s 4G Smartphone (4 GB RAM, 128 GB)",
    brand: "vivo",
    category: "Mobiles",
    price: 11999,
    mrp: 15999,
    rating: 4.4,
    reviews: 2134,
    image: "/original-assets/vivo-y17s-forest-green-4gb-ram-128gb-storage-250x250.webp",
    badge: "Bestseller",
    stock: 34,
    seller: "Shopin Retail",
    description:
      "A stylish everyday smartphone with a bright display, capable cameras and dependable all-day battery.",
    features: [
      "8 GB RAM + 128 GB storage",
      "50 MP main camera",
      "5000 mAh battery",
      "Fast and secure side fingerprint",
    ],
  },
  {
    id: "p2",
    title: "OnePlus Nord CE 5G Smartphone",
    brand: "OnePlus",
    category: "Mobiles",
    price: 24999,
    mrp: 29999,
    rating: 4.5,
    reviews: 1847,
    image: "/original-assets/oneplusNord5G.jpg",
    badge: "Top Deal",
    stock: 20,
    seller: "Nova Gadgets",
    description:
      "Smooth 5G performance with a fluid display and a clean software experience.",
    features: [
      "5G ready",
      "120 Hz display",
      "256 GB storage",
      "67 W fast charging",
    ],
  },
  {
    id: "p3",
    title: "Wireless ANC Earbuds with 40H Playback",
    brand: "Soundcore",
    category: "Electronics",
    price: 1899,
    mrp: 4999,
    rating: 4.2,
    reviews: 8921,
    image: "/products/earbuds-product.svg",
    badge: "Hot Deal",
    stock: 87,
    seller: "Audio Hub",
    description:
      "Immersive true wireless audio with active noise cancellation and a pocket-sized case.",
    features: [
      "Active noise cancellation",
      "40 hour total playback",
      "Low-latency gaming mode",
      "Dual-device pairing",
    ],
  },
  {
    id: "p4",
    title: "4K Smart LED Google TV 43 inch",
    brand: "VisionPlus",
    category: "Appliances",
    price: 28990,
    mrp: 39990,
    rating: 4.3,
    reviews: 1062,
    image: "/products/tv-product.svg",
    badge: "Bank Offer",
    stock: 15,
    seller: "HomeTech Store",
    description:
      "Borderless 4K entertainment with smart streaming, HDR support and cinematic sound.",
    features: ["43-inch 4K UHD", "Google TV", "HDR10", "Dolby Audio"],
  },
  {
    id: "p5",
    title: "Nikon Z5 Mirrorless Camera with 24-200mm Lens",
    brand: "Nikon",
    category: "Electronics",
    price: 54990,
    mrp: 65990,
    rating: 4.7,
    reviews: 734,
    image: "/original-assets/z-24-200mm-z5-nikon-original-imag2zuekuxgxsgg.webp",
    badge: "Premium",
    stock: 9,
    seller: "Camera World",
    description:
      "Capture detailed photos and smooth video with a creator-friendly mirrorless setup.",
    features: [
      "24 MP sensor",
      "Interchangeable lens mount",
      "4K video",
      "Wi-Fi and Bluetooth",
    ],
  },
  {
    id: "p6",
    title: "Men Solid Slim Fit Casual Shirt",
    brand: "Roadster",
    category: "Fashion",
    price: 699,
    mrp: 1499,
    rating: 4.1,
    reviews: 5413,
    image: "/products/shirt-product.svg",
    badge: "60% OFF",
    stock: 64,
    seller: "StyleKart",
    description:
      "A versatile cotton-blend shirt designed for easy everyday styling.",
    features: [
      "Regular collar",
      "Cotton blend",
      "Slim fit",
      "Machine washable",
    ],
  },
  {
    id: "p7",
    title: "Women Printed Straight Kurta Set",
    brand: "Sangria",
    category: "Fashion",
    price: 999,
    mrp: 2499,
    rating: 4.4,
    reviews: 2186,
    image: "/products/kurta-product.svg",
    badge: "New",
    stock: 37,
    seller: "StyleKart",
    description:
      "Comfortable printed kurta set for everyday and festive wardrobes.",
    features: [
      "Rayon fabric",
      "Straight fit",
      "Printed pattern",
      "Includes bottoms",
    ],
  },
  {
    id: "p8",
    title: "Running Shoes for Men - Lightweight Cushion",
    brand: "Campus",
    category: "Sports",
    price: 1299,
    mrp: 2499,
    rating: 4.3,
    reviews: 3785,
    image: "/products/running-shoes-product.svg",
    badge: "Best Value",
    stock: 45,
    seller: "SportZone",
    description:
      "Lightweight running shoes with cushioned support for daily walks and workouts.",
    features: [
      "Mesh upper",
      "EVA cushioning",
      "Lace-up closure",
      "Flexible outsole",
    ],
  },
  {
    id: "p9",
    title: "5-Star Inverter Split AC 1.5 Ton",
    brand: "Voltas",
    category: "Appliances",
    price: 33990,
    mrp: 48990,
    rating: 4.2,
    reviews: 468,
    image: "/products/ac-product.svg",
    badge: "Energy Saver",
    stock: 11,
    seller: "Appliance House",
    description:
      "Efficient cooling for medium-sized rooms with inverter technology.",
    features: [
      "1.5 ton capacity",
      "5-star energy rating",
      "Copper condenser",
      "Turbo cooling",
    ],
  },
  {
    id: "p10",
    title: "Front Load Fully Automatic Washing Machine 7 kg",
    brand: "LG",
    category: "Appliances",
    price: 27990,
    mrp: 35990,
    rating: 4.5,
    reviews: 931,
    image: "/products/washing-product.svg",
    badge: "Top Rated",
    stock: 13,
    seller: "Appliance House",
    description:
      "Quiet, efficient washing with multiple wash programs and smart diagnostics.",
    features: [
      "7 kg capacity",
      "Fully automatic front load",
      "Steam wash",
      "Inverter motor",
    ],
  },
  {
    id: "p11",
    title: "6-Seater Engineered Wood Dining Table Set",
    brand: "Wakefit",
    category: "Home",
    price: 16990,
    mrp: 22990,
    rating: 4.4,
    reviews: 318,
    image: "/products/dining-table-product.svg",
    badge: "Home Pick",
    stock: 7,
    seller: "Home Studio",
    description:
      "A clean-lined dining set made for contemporary homes and everyday family meals.",
    features: [
      "6-seater",
      "Engineered wood",
      "Easy assembly",
      "Scratch-resistant finish",
    ],
  },
  {
    id: "p12",
    title: "Air Fryer 4.2 L with Digital Touch Panel",
    brand: "Philips",
    category: "Appliances",
    price: 5499,
    mrp: 8999,
    rating: 4.6,
    reviews: 6241,
    image: "/products/air-fryer-product.svg",
    badge: "Bestseller",
    stock: 29,
    seller: "Kitchen Plus",
    description:
      "Crispy cooking with less oil, presets and an easy digital touch interface.",
    features: [
      "4.2 L capacity",
      "Touch controls",
      "Preset cooking modes",
      "Rapid air technology",
    ],
  },
  {
    id: "p13",
    title: "Vitamin C Brightening Face Serum 30 ml",
    brand: "Minimalist",
    category: "Beauty",
    price: 599,
    mrp: 699,
    rating: 4.4,
    reviews: 8115,
    image: "/products/serum-product.svg",
    badge: "Trending",
    stock: 104,
    seller: "Glow Store",
    description:
      "A lightweight daily serum formulated for brighter-looking, more even-toned skin.",
    features: [
      "Vitamin C formula",
      "30 ml bottle",
      "Lightweight texture",
      "Suitable for daily use",
    ],
  },
  {
    id: "p14",
    title: "Hair Dryer 2000W with Cool Shot",
    brand: "Nova",
    category: "Beauty",
    price: 899,
    mrp: 1799,
    rating: 4.1,
    reviews: 2911,
    image: "/products/hair-dryer-product.svg",
    badge: "Value Deal",
    stock: 72,
    seller: "Glow Store",
    description:
      "Quick drying with heat settings and a cool shot for everyday styling.",
    features: [
      "2000 W motor",
      "3 heat settings",
      "Cool shot",
      "Concentrator nozzle",
    ],
  },
  {
    id: "p15",
    title: "Almonds 1 kg Premium California",
    brand: "FarmFresh",
    category: "Grocery",
    price: 799,
    mrp: 1099,
    rating: 4.5,
    reviews: 1124,
    image: "/products/almonds-product.svg",
    badge: "Fresh Pick",
    stock: 58,
    seller: "FarmFresh",
    description:
      "Crunchy premium almonds for snacking, baking and everyday nutrition.",
    features: [
      "1 kg pack",
      "Premium California almonds",
      "Resealable pack",
      "Vegetarian",
    ],
  },
  {
    id: "p16",
    title: "Cold Pressed Groundnut Oil 1 L",
    brand: "Fortune",
    category: "Grocery",
    price: 179,
    mrp: 229,
    rating: 4.3,
    reviews: 723,
    image: "/products/oil-product.svg",
    badge: "Everyday Low",
    stock: 120,
    seller: "Daily Needs",
    description:
      "A kitchen staple with a clean, nutty profile for everyday cooking.",
    features: [
      "1 litre pack",
      "Cold pressed",
      "Vegetable oil",
      "Sealed packaging",
    ],
  },
  {
    id: "p17",
    title: "Laptop Backpack 25 L Water Resistant",
    brand: "Wildcraft",
    category: "Fashion",
    price: 1299,
    mrp: 2499,
    rating: 4.5,
    reviews: 4877,
    image: "/products/backpack-product.svg",
    badge: "Popular",
    stock: 38,
    seller: "Travel Gear",
    description:
      "A roomy everyday backpack with organized pockets and water-resistant fabric.",
    features: [
      "25 litre capacity",
      "Laptop compartment",
      "Water resistant fabric",
      "Padded shoulder straps",
    ],
  },
  {
    id: "p18",
    title: "Mechanical Gaming Keyboard RGB",
    brand: "Redragon",
    category: "Electronics",
    price: 2299,
    mrp: 3999,
    rating: 4.4,
    reviews: 2140,
    image: "/products/gaming-keyboard-product.svg",
    badge: "Gaming",
    stock: 26,
    seller: "Byte Store",
    description:
      "Tactile mechanical keys with vibrant RGB lighting and a sturdy compact chassis.",
    features: [
      "Mechanical switches",
      "RGB backlight",
      "Anti-ghosting",
      "Detachable cable",
    ],
  },
];
